import { Link } from 'react-router-dom';
import { BitCharacter } from '../../../components/landing/BitCharacter.jsx';
import { goalTypeMeta, formatGoalDate } from '../../goals/goals.domain.js';
import { useDailySummary } from '../useDailySummary.js';
import { displayNumber } from '../daily-summary.domain.js';
import { JourneyError, SectionLoading } from '../../progress/components/JourneyUI.jsx';
import journey from '../../progress/Progress.module.css';
import styles from '../DailyOverview.module.css';
export function DailyOverviewContent({ data }) {
  const { nutrition: n, activity, targetContext } = data;
  const remainingLabel = n.remainingCalories == null ? 'Calories remaining unavailable' : n.remainingCalories < 0 ? 'kcal over target' : 'kcal remaining';
  return <div className={`${journey.scope} ${styles.overview}`}>
    <section className={styles.hero} aria-label="Daily calorie summary"><div className={styles.heroCopy}><p className={styles.eyebrow}>Your day, in focus</p><div className={styles.calorieNumber}>{displayNumber(n.remainingCalories == null ? null : Math.abs(n.remainingCalories), 0)}</div><h2>{remainingLabel}</h2><p className={styles.heroNote}>{n.remainingCalories == null ? 'Your logged activity is here. A few details are needed for the full picture.' : n.remainingCalories < 0 ? 'One day is part of a bigger picture. Keep logging what matters.' : 'A little awareness goes a long way.'}</p></div><div className={styles.bit}><BitCharacter state="pointing" decorative /></div><dl className={styles.calorieFacts}>{[['Consumed', n.consumedCalories], ['Burned', n.burnedCalories], ['Target', n.targetCalories]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{displayNumber(value, 0)} <small>{value != null ? 'kcal' : 'unavailable'}</small></dd></div>)}</dl></section>
    {!n.burnedCaloriesComplete && <div className={styles.context} role="status"><strong>Burned calories unavailable</strong><p>A completed workout has no calorie estimate. Burned and remaining calories can’t be calculated reliably for this day.</p></div>}
    {n.targetCalories == null && <div className={styles.context}><strong>No target available for this day.</strong><p>Spotter needs a goal, body basics, activity level, and an available weight for this date. Your logged nutrition still counts.</p><Link to="/app/profile">Review profile →</Link><Link to="/app/goals">View goals →</Link></div>}
    <section className={styles.macros} aria-labelledby="daily-macros-title"><div className={styles.macroHeading}><div><p className={styles.eyebrow}>Fuel for your rhythm</p><h2 id="daily-macros-title">Make room for balance.</h2></div><span>Consumed / target</span></div><div className={styles.macroRows}>{[['Protein', n.protein], ['Carbs', n.carbohydrates], ['Fat', n.fat]].map(([label, macro]) => <div key={label} className={styles.macro}><h3>{label}</h3><p><strong>{displayNumber(macro.consumed)}</strong><span> / {displayNumber(macro.target)} g</span></p>{macro.consumed != null && macro.target != null && macro.target > 0 ? <progress max={macro.target} value={Math.min(macro.consumed, macro.target)} aria-label={`${label}: ${displayNumber(macro.consumed)} of ${displayNumber(macro.target)} grams`} /> : <span className={styles.unavailable}>Progress unavailable</span>}</div>)}</div>{!n.macrosComplete && <div className={styles.macroNote} role="status"><strong>Macro totals incomplete.</strong> Some logged foods don’t include complete nutrition data. Calories are still shown above.</div>}</section>
    <section className={styles.activity} aria-label="Daily activity"><Link to={`/app/meals?date=${data.date}`}><span className={styles.activityIcon} aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 11h18M5 11c0 5 3 8 7 8s7-3 7-8M8 4v3m4-3v3m4-3v3" /></svg></span><div><p>Meals</p><h3>{activity.mealsLogged} {activity.mealsLogged === 1 ? 'meal' : 'meals'} logged</h3><span>View meals →</span></div></Link><Link to={`/app/training/history?date=${data.date}`}><span className={styles.activityIcon} aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M6 8v8M3 10v4m15-6v8m3-6v4M6 12h12" /></svg></span><div><p>Training</p><h3>{activity.workoutCompleted ? 'Workout completed' : `${activity.workoutsLogged} ${activity.workoutsLogged === 1 ? 'workout' : 'workouts'} logged`}</h3><span>View training →</span></div></Link></section>
    {targetContext && <details className={styles.targetContext}><summary>Targets based on your {goalTypeMeta(targetContext.basedOn.goalType).label.toLowerCase()} goal</summary><p>Using {displayNumber(targetContext.basedOn.weightKg)} kg, recorded {formatGoalDate(targetContext.basedOn.weightRecordedAt, { short: true })}.{targetContext.basedOn.targetWeightKg != null && ` Target: ${displayNumber(targetContext.basedOn.targetWeightKg)} kg.`}{targetContext.basedOn.targetDate && ` Target date: ${formatGoalDate(targetContext.basedOn.targetDate, { short: true })}.`}</p>{targetContext.disclaimer && <p>{targetContext.disclaimer}</p>}</details>}
    <Link to="/app/progress" className={styles.journeyLink}><div><p className={styles.eyebrow}>Zoom out</p><h2>Today is part of your story.</h2><p>See how your body and goal are changing over time.</p></div><span>View progress ↗</span></Link>
  </div>;
}
export default function DailyOverview({ date }) {
  const query = useDailySummary(date);
  if (query.isPending) return <div className={styles.loading}><SectionLoading label="Loading daily calories" height="340px" /><SectionLoading label="Loading macros" height="180px" /><SectionLoading label="Loading daily activity" height="130px" /></div>;
  if (query.isError) return <div className={journey.scope}><JourneyError error={query.error} onRetry={query.refetch} /></div>;
  return <DailyOverviewContent data={query.data} />;
}
